### PR TITLE
New error code added

### PR DESCRIPTION
**Pull request by akhrol**
805 This user is not allowed to use this method

### CODE REVIEW

**Comment by apheleia** [comment]
Great!

**Comment by apheleia** [comment]
@akhrol can you also add the error code to the overview of all error ocdes?

**Comment by akhrol** [comment]
it is already added: https://github.com/PlugSurfing/oioi-documentation/pull/60/files#diff-b3ce4a4f21b247fb0f6195997d2cf4e1

**Comment by apheleia** [comment]
Nice! 💪

**Pull request merged**
